import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< Updated upstream
  title: "tee riffic",
  description: "Say it loud, say it proud, design your tee in the crowd.",
=======
  title: "",
  description: "Generated by create next app",
>>>>>>> Stashed changes
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
